<?php
/**
 *  文件：BaseController.php
 *  author:daixianhua
 *  时间：2020/7/5-16:24
 */


namespace app\index\controller;


use think\Controller;

class BaseController extends Controller
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}